[STARTAI-11] Fit different implemented models
PNUAITeam13/AlcoholConsumption pull request #7
Opened 2023-11-14 09:22 UTC by nasstis

2023-11-14 11:12 UTC, ArsenOOO7 requested changes
Good job, but please create dictionary with models, for instance:
```
models = {
   'Linear SVM Classifier model': LinearSVC(max_iter=1000, dual=False)
   ...
}
```

And function, that will fit these models, something like was done in our intermediate machine learning course. [Look here](https://github.com/PNUAITeam13/intermediate_ml_works/blob/main/exercise-introduction.ipynb), function ```scoreModel```

2023-11-20 12:42 UTC, JJerome-NM approved these changes

2023-11-20 12:50 UTC, ArsenOOO7 commented
Just one more
![зображення](https://github.com/PNUAITeam13/AlcoholConsumption/assets/30925793/882b3972-ac12-492a-a8ae-7ffeb32e0036)

Please make return predicted values

And try to avoid such constructions if u need to return value at the end
I mean
```
if something:
  ...
  return result
 
if something_1:
  ...
  return result_1
 
...
return result_3
```

2023-11-20 18:45 UTC, ArsenOOO7 approved these changes

2023-11-21 10:28 UTC, merged