[STARTAI-15] Upgrade linear regression
PNUAITeam13/AlcoholConsumption pull request #9
Opened 2023-11-14 13:38 UTC by nasstis

2023-11-14 14:26 UTC, ArsenOOO7 commented on linear/linear_regression_multiple_features.py
> +class LinearRegressionMultipleFeatures:
Format

2023-11-14 14:29 UTC, ArsenOOO7 commented
Pls check if matplotlib can build such graphs
If it's possible, add new static function to our visualize helper
And draw it after
![зображення](https://github.com/PNUAITeam13/AlcoholConsumption/assets/30925793/6883408a-b2bb-402b-b4e6-62701ffd8f8f)

2023-11-14 14:40 UTC, mesnuk approved these changes

2023-11-14 20:18 UTC, JJerome-NM requested changes
In general, everything looks good, but think about the proposed changes

2023-11-14 20:18 UTC, JJerome-NM commented on linear/linear_regression_multiple_features.py
> +        self.loss_history = []
I think `m, b and loss_history` can be private?
Also, are you sure that they should be declared in the init?

2023-11-14 20:18 UTC, JJerome-NM commented on linear/linear_regression_multiple_features.py
> +        self.b -= self.__learning_rate * (1/X.shape[0]) * np.sum(errors)
I think the formatting is still not exactly right

2023-11-20 18:34 UTC, JJerome-NM approved these changes
Look good

2023-11-21 10:22 UTC, merged